### ISSUE TITLE
Really hope you can share your dataset!

### ISSUE THREAD

**Issue by zwlshine** [ardamavi/3D-Medical-Segmentation-GAN#1]

**Comment by ardamavi** [comment]
In the construction phase. A comprehensive documentation will be published very soon.

**Comment by XYZ-916** [comment]
I'm looking forward to your dataset too! Thank you~

**Comment by ardamavi** [comment]
In README file:
Currently Used Dataset is DEU Liver Segmentation Dataset: https://eee.deu.edu.tr/moodle/mod/page/view.php?id=7872

You must apply for getting dataset.
