### ISSUE TITLE
Something About the Data Generator

### ISSUE THREAD

**Issue by XYZ-916** [ardamavi/3D-Medical-Segmentation-GAN#2]
`  # Discriminator Training:
        for i in range(int(batch_num/4)):
            # Getting generated data:
            getted_generator_data = next(data_generator)
            generator_pred = Generator.predict(getted_generator_data[0])

            # Getting real data:
            getted_real_data = next(data_generator)`

As seen above, the real data is got by "getted_real_data = next(data_generator)". I'm confusing about the operation. Can you give me a detail explanation of it? Thank you~

**Comment by ardamavi** [comment]
'data_generator' is a python Generator object. For getting next packet from Generators, we use 'next()' function.
