### ISSUE TITLE
How to change the data from dicom to .nii

### ISSUE THREAD

**Issue by songwaimai** [ardamavi/3D-Medical-Segmentation-GAN#5]
Thanks your sharing! I am a newbee to process the medical images. Do you try the method on MRI data, i want to run the code on MRI(.nii), but i don not know how to modify your get_dataset.py.  I'd appreciate it if you could give me a little guidance or advice~

**Comment by ardamavi** [comment]
We are planning to work with MR images with our new version.
You can look up `NiBabel` library for reading `.nii` files.

**Comment by songwaimai** [comment]
Do you have published the related paper based on your code?? Could you send me the link or the paper to let me learn~ thank you~

**Comment by ardamavi** [comment]
Sorry, we don't have a publication.

**Comment by life-8079** [comment]
hi，Could you modify get_dataset.py(nii to h5) successfully?
